package day1;

import java.util.ArrayList;
import java.util.HashMap;

public class part1 {
    private static final String input = "six1mpffbnbnnlxthree\n" +
            "4eight3one92\n" +
            "9nine2xnhvjtjlzj48\n" +
            "jxrbrt4jmnmlonesznvbjrsn\n" +
            "nsvkljgpfn77pvfour5j\n" +
            "fourlkgmnnzncht75\n" +
            "shqmhnlbjjvskone6two78\n" +
            "qjgcxccgthree85five\n" +
            "eight7sbdbgqgcfive3two\n" +
            "eight878nckqdt3pgzc\n" +
            "pkdrhksqdhrvhg5\n" +
            "nine7four7one2\n" +
            "9fives\n" +
            "fplzzhthreethree7sqnsmrljgsmnpktfkhzdpqfkone\n" +
            "hqrcls33sevensevennine\n" +
            "four4m\n" +
            "seven331fivekfrqbd\n" +
            "ninechvkpthreefive8tlmfclr\n" +
            "8954bxsqntndjmonenx5\n" +
            "nine7km\n" +
            "seven588sevenxffivethreehkrczrlm\n" +
            "3cmjzjmhone\n" +
            "jfgr2fourtflvttr\n" +
            "qpplcgvklzztqjkbbnfiveftcqmlrqnd824\n" +
            "ttsgz9\n" +
            "9eightthreeonezrninetwo\n" +
            "pbccq6onefoureightbkvgvtm3\n" +
            "9tworrchzdzfthreefgksrzjpdq\n" +
            "chcjdxbninejtwo1nineszf2one\n" +
            "ronecfcdlsqgfvlxj217\n" +
            "three4onex1\n" +
            "8nrhcn3zgsgn3239\n" +
            "3tczzbrvdm6tphb32\n" +
            "85threecnqsscqklhsix\n" +
            "5foureightnine57nshjbgrv\n" +
            "1fourpcgljhlx5\n" +
            "v632eightnnjrjl\n" +
            "zlpfive6xthreeczrknclqdtfiveseven\n" +
            "6ninekbdmjqrktwo2\n" +
            "threetwofourlqjnmnine767\n" +
            "8two5mbs3eightthreethreelvhcgrd\n" +
            "zntoneightfour1lcbzfhm4msneight7\n" +
            "7eight5eightone\n" +
            "8rpbfqb44\n" +
            "rfninelkclkflsjsrb3\n" +
            "jzxlngk1\n" +
            "5zsnxfdt82qmszx\n" +
            "75threetcvbmhplqmhrcztsghctvsvrhkftwo\n" +
            "grtwosnjvrpx76\n" +
            "69two1tdsgbgbprs7\n" +
            "vrsrmdngjpn2nine\n" +
            "onesix44vgdtwo\n" +
            "phtfxkmbfbm61one4pxnvnvld6\n" +
            "hfsmptwo6dtlnfnmtmrpgmr\n" +
            "jgrbttcmfkkbrdeight846dzgdjxd3\n" +
            "jdsfprdmhpvzqbgjdgdvkhmtqzxgm8flhxfive\n" +
            "qj36gfj\n" +
            "3twonine\n" +
            "bszc6bvfkfjbbh\n" +
            "4sevenfive4one\n" +
            "fourhxkhxtvtblsevenonekgnpnjqq46ctvmzkqvxdl\n" +
            "6989hvr4258\n" +
            "seveneightfivegbzczonerqkdvsfour6\n" +
            "326sevenoneeightfour\n" +
            "41five8one3\n" +
            "zrtnkqtqfive91bxfctxnk\n" +
            "t226n6xnrdeight5\n" +
            "one5onetlzbbxchgfhzgx\n" +
            "five5seven8\n" +
            "1pnvdbvl2zrjpbkbpthree\n" +
            "tlctwone39zfdqtnjshzjrqkcdnjnszrdfive\n" +
            "snklklhpcclkrtkn2eight15three8\n" +
            "7threeplhsfsevenbgbbnineftvjbnvxpsm\n" +
            "5dtxxthtphbnc\n" +
            "six7four\n" +
            "djsvntknhnqv2qrvnrz\n" +
            "twosevenbzvfzpbonenine5\n" +
            "1tq2eightseven3sixvjvnkqq4\n" +
            "z55\n" +
            "4mthgcrfbcvphfmglvcjsl8pctb\n" +
            "6jgptkgcl43bthreetjfxchtxlf5\n" +
            "5zxgktvdnninenine9\n" +
            "lhdfivevxrgpkpzrzjlg5mk\n" +
            "oneseven4seven6njmkvkpjmg\n" +
            "cblmbxlthtfqfk59three8\n" +
            "xxcnvsfour298mqqrbcn\n" +
            "lbvmgdpgbd3hgmpthreefourjbdbfvvv5vfqrd4\n" +
            "vsxshfhftrgpstxtj94xnxrntxnlcgtdjtqpbmh\n" +
            "six7fournrmdgzldndnrgrkxlbtdonemjftskhhm4\n" +
            "1sixtwoseventwofivezbsdvdqncffourkknlsx\n" +
            "78mqspvdsb2\n" +
            "teight4skkdlfcsrc38jfjtmfour2\n" +
            "3pgbppzbmlbsevensix533one\n" +
            "hzrfpeighthjrf4kqttngxfivefivehzvxnzfk4\n" +
            "18zldlpktnceight\n" +
            "six6lvnt6k\n" +
            "28sixs\n" +
            "348lmkg9one4\n" +
            "4ninesnqqzoneltjhsjjbnp2\n" +
            "rckbvndsjm99six2nine\n" +
            "eight5vhjvgrrthreetwo6\n" +
            "2fourseven1oneights\n" +
            "7threeonethreex\n" +
            "662dvrszddqqtwoeightsixeight9\n" +
            "xftcvpmkl2threecdqsix48kgfktcdn8\n" +
            "3rcgdrjcnmb\n" +
            "4three5\n" +
            "two3twotwonine7ljonezh\n" +
            "17mdbr9ninehhs3\n" +
            "nchgkdvbm8onebhdtmgdgkqjfour\n" +
            "1eightpqbslptjfgninenine72\n" +
            "1ghpjmc4q\n" +
            "245seventgftbfkbnztwoone\n" +
            "94gxjjlptflxsvsrxxone\n" +
            "seven3three\n" +
            "7foureight\n" +
            "mxgc6\n" +
            "sixthree6rrdntczlrrnsnine\n" +
            "9three4nd1eightseven\n" +
            "ndeightwosnlvkv8jdllrtwo741\n" +
            "threefour6bkscthreeeight\n" +
            "hffoneight96vqkbsgpzvn3sixtxh4ckjlm3\n" +
            "vc6tnine5mfplhklmv\n" +
            "zoneight35ninefour1q5ssmjtf\n" +
            "rkblg8tzdjhrsdxbcx\n" +
            "kgvqtxzjr56psfour9\n" +
            "6dtbh67five\n" +
            "qjx4two2ls\n" +
            "hfstd58three65twosbxll\n" +
            "g2twosixvlvtt\n" +
            "sevensix4nineonetvfcctgnj\n" +
            "tkjbktckztwozzstwo7jgxbxxrkzx\n" +
            "8gftwosjkhqxvfpqrsrseven\n" +
            "sevenkphl9eight91onesxjvtfdccd\n" +
            "lcrvslcc6bhzlcmz\n" +
            "bbxdjdfprnjtxhsevendzsbczc6one\n" +
            "one5m29\n" +
            "h3one\n" +
            "sixtjdgzvfqpjvdthree421x7\n" +
            "eightfiveeight8sbmspqltvsxsix\n" +
            "four8two\n" +
            "5sixfour94961\n" +
            "9two6onenjfsnqnmfc\n" +
            "fivethree8six3l\n" +
            "1twokzqnbclbqgtbeightrtwo\n" +
            "7csgktwooneone\n" +
            "75nine8two\n" +
            "fourrj5tfdrlgdzrfptxvnine\n" +
            "four4seven5eight\n" +
            "6onesixtpsgqgk5seven\n" +
            "qpznmcmfgpfqmzvkthdseven93threersxsktrkk99\n" +
            "587nine6eightseventhreeqmjv\n" +
            "zfssixvkhtlcmltwo7\n" +
            "8bqvgfnzg\n" +
            "6l2eighttjtgrj1knrtjqrpjd\n" +
            "lmjbs6ninethreeeight58\n" +
            "1ktxhfzkgrfmtthree\n" +
            "xtmfsxsdfgfivethreefour9fnjcmbdz\n" +
            "vlhlhzsevenonelhql285xccp\n" +
            "3172bndlm4sevenpnz\n" +
            "6sbzqfftqnfourhktmxxqkthreepzkjvfxxfour\n" +
            "sevenfoursix544nineqr\n" +
            "9eightsevensevenqrxjzmmfjnd\n" +
            "ceightwogntfttkkkdpsq3\n" +
            "gpmtpbchjdpgmkone8sixmhm53\n" +
            "ndfz9twoonelprmtwoslvvp3\n" +
            "njrtr14sevenninevmnbone\n" +
            "1q\n" +
            "seven1eight\n" +
            "svstnvxdbmseven9pbfrsgvlhd398\n" +
            "3ninefivelbcxcfcc\n" +
            "9njgmxpeightpqgj\n" +
            "three6636bbqrtxprjb4onetkkgxxmtv\n" +
            "7ssrrsfourfournine\n" +
            "4one1eightzgcpkgbpgmsevenninetwonetk\n" +
            "threelpmgdpmmsevenxkphrddr5two9\n" +
            "plpzz4\n" +
            "91fiveg\n" +
            "fournnjzsnrqzbdggldr9\n" +
            "llnsix5sevenfive45threeone\n" +
            "xxnftztcbzrptthreervfiveseven9sevenlnxhzvk\n" +
            "glceightwo4eightnineeight9fpbp\n" +
            "six6eightfour1fjlmmqlqszvkbspshcvnjlxfvmm\n" +
            "6sevenfourmnv1qcf2khfjclcsx\n" +
            "fivebsvvnhgcp6jdqrcfreightwohfh\n" +
            "9eight5onerjvcdct5\n" +
            "jb81onefournine35tftlzn\n" +
            "59sevenpcfninevtrrrhmeight\n" +
            "hkphm7five\n" +
            "8ttb\n" +
            "eight9five85pxv\n" +
            "72threepsixgrvfourgbbgbgprtxmhlz\n" +
            "1pgdjtmkntbjfckgq\n" +
            "9brqcqvqgzgpgtvbtktxkxjnine4\n" +
            "26fourtwo8\n" +
            "six3tncnc6pbjkbkgninenssjbgqdpeight\n" +
            "sixrjtfbdlrv5rdmpbqfxfxrccs\n" +
            "kmbcgt81seven9jsnvdtwo1\n" +
            "9sixseven49hzxlf\n" +
            "jmcssix7onesix\n" +
            "pzttczmzhgtgtvvlhpkv5jnjqnxkhceightfivepnfn\n" +
            "1955xv\n" +
            "sixthree247nine1\n" +
            "jfdgxhkfour1eight1six2\n" +
            "threefrdlbmnqrreight4psfonegggjj\n" +
            "391eightfour54nine\n" +
            "95five6\n" +
            "dqvseven8five\n" +
            "3onetwo1fivexppqsltgtwosfb4\n" +
            "6fivetwo\n" +
            "5eight4j\n" +
            "7l\n" +
            "7khdvfks5threesix2\n" +
            "46fivethreezfszfkxctworjgtwoghrtpz\n" +
            "threetwokjdljphg5onefoursevensevenjnc\n" +
            "rddxs722cg\n" +
            "pkpsgblkvsevennstsqvh3twofivekkhzzhqxjjsbvvvvnine\n" +
            "fivethree77one\n" +
            "63twonine727\n" +
            "sglzpbvhccdvdnzdsixthreem6fivesix\n" +
            "ldmtseven7nkhsqkklmzltxvmkrq1\n" +
            "59kfncssdeight6three7\n" +
            "zhltwonejbmfvmsix43\n" +
            "73twoninesevensix3\n" +
            "five4three5eightsixgvfour\n" +
            "twovsrjkxtjj5gmbvfiveqmqscfqpsix\n" +
            "sixzdbfgtzk8zhthreecdvvqjbvrcphvhqmlxmfive\n" +
            "nrppflfnine7nd9tfseven\n" +
            "3nrclsix\n" +
            "dveightfive1\n" +
            "3qrdtsfmktwo\n" +
            "ppeightwo4one3\n" +
            "159pfsbninezgbpvqggfbfxcqzb9\n" +
            "lrhzqtjrdxrfpbskrseven5qqrnsh\n" +
            "nine51twothree12\n" +
            "2six5fivehs\n" +
            "45sixtwothreeone45\n" +
            "kjkfggmzqxrjl4\n" +
            "four5five\n" +
            "srtgklg3fjb92seven56mrk\n" +
            "eightzlmsmnthreetwofour324\n" +
            "fivefiveninepvfsxponextzdmft4\n" +
            "vneightwonine7ntgxbzfouronetwofzzgkkhtx3nine\n" +
            "ndcvzhxbrqmfjcjpzffourfive4gzkxzzlsqn1fjdb\n" +
            "2799ph\n" +
            "6nine77twoznzbjnjhkqljmsmnj\n" +
            "bkzttcjdmpdclpzmpxj67tfour\n" +
            "6btjcjxsevenfcgbjjsxhmlklvzv\n" +
            "four9vpfpknine\n" +
            "onesrjxsfncglvkzs5tpr\n" +
            "qgf782lqzvqztbqjqrqdnfpkthree\n" +
            "seven8f3four\n" +
            "sevenpkksntfdlqxvqjfgfourztpbglbhmhlfftmxtp54\n" +
            "6fourseven4eight\n" +
            "9lfcjnfournine\n" +
            "four8fiveseven7threecz\n" +
            "rfnveight9threetwo5three\n" +
            "tml98ckph\n" +
            "z4krthreeeightfour3\n" +
            "six3fhsixxdpmszsbeighthlgd4\n" +
            "9hbnqkhsndvsevencrl1six5hzg8\n" +
            "6two5three5\n" +
            "qplckfdsgd2fivefourfivefsix\n" +
            "ninebfour26fivetwonem\n" +
            "hmbkjkdtnfnzs6\n" +
            "325lpxntm\n" +
            "lxtsevenfqpc7jvvtbppczsrmfour\n" +
            "threepfpnbkvq59fgmsrglvcfivenhb\n" +
            "5cmq8vxdn2nine\n" +
            "zpzvknntdf1threefour2zdh\n" +
            "five399kgztnine\n" +
            "nmddfssix3sevendrbt\n" +
            "seven7fivebr5xc\n" +
            "177two\n" +
            "3four38six6\n" +
            "eight9four\n" +
            "49llmpmzkfgsevenrrbdzk4\n" +
            "four23ceightxxthtplmk\n" +
            "qmjjvkfd34qkkd3\n" +
            "foursevenrgjxsvlkz7173kr\n" +
            "three82fivermfnqgcfourtbtnpjfnk\n" +
            "744mpdkhr87\n" +
            "75qfzxshzphsnineone8\n" +
            "two6five\n" +
            "fourbhgndsgmceight3\n" +
            "2one186\n" +
            "833xjbcqdgmeightfive\n" +
            "pfgt93bkzrzbthnssevenczvkfklkbpgnjt\n" +
            "dlsix8seven5\n" +
            "4two4\n" +
            "qtblgfgms6lsctgslddgpnx1cxrmbnjconeslscbqvljpfive\n" +
            "mllxhpd5\n" +
            "kfvjhcz9seven16\n" +
            "eight36\n" +
            "633793\n" +
            "phqeightwomd27eightqkcltdfourx\n" +
            "2fiveonednjb6ninepznvnhrbvdsdnine\n" +
            "8eightfhjdzzhmct74three\n" +
            "vxps976\n" +
            "threethreebbninefive9\n" +
            "6xdttgthree9rpg\n" +
            "fivedfbkffgldktbt6fiveqlxcznqxlgltc9\n" +
            "4ltnlkdmthree7gcbqnskeightseven\n" +
            "onefournsjgbcn34fouronexjxd\n" +
            "169326srhszxcrn1\n" +
            "5meight6dfive\n" +
            "kztjjnknine2eight87nineskqjpvn6\n" +
            "seven3four96\n" +
            "8four5kkgmppkt\n" +
            "52six8fourvtdrcj7five\n" +
            "9tgbcxcvggv4ninettxjrjv\n" +
            "ninepdmghhq5sixtwo\n" +
            "fivexvfdone14\n" +
            "foursevenfourfqjqthreefour4qcvqglr\n" +
            "four9sixtwo48\n" +
            "pzvrgmbvngtvcmmgthreepvb7sevenfvhxchplsfsdcltwo\n" +
            "gkrnmzzrd3\n" +
            "nine2qzgltqninelrnlrjzn923kkpmpm\n" +
            "7tts7qmbthree4539\n" +
            "sevenone9ghdb8\n" +
            "jvcc18fourninetwoqvkg7three\n" +
            "four4onenine\n" +
            "19vbsdkslnn6sevenktkqmcp4\n" +
            "n6\n" +
            "7psthfqcfd\n" +
            "99nineeight861\n" +
            "1four3eightbkfnrdcqdqdmkgfzbbn6\n" +
            "27nlcslnseven5hdvsix8\n" +
            "9nbzzjjsvtwoxg3seven3nine\n" +
            "7sixnhldjcjfsgvpxrsnxtcblpgvcvjrmkhzx\n" +
            "2726nsdtb1\n" +
            "2five3six5three3mhnclq\n" +
            "sevenfivetwo1fivekpxrpjkgktwo\n" +
            "7one4tnkqfvqlmjrzlqflnrsf\n" +
            "nvlkqzjt2nineseven28\n" +
            "ltqschggjgrrxbtfz3onesevencpzbffbvzhpgzmlmxxbqjrtxc\n" +
            "518sixeightwop\n" +
            "cctwonetfmvjx78\n" +
            "2jvrvcsevenlglmgblbfive\n" +
            "7seven1fivevlbhbsk\n" +
            "48one4cn6\n" +
            "3one6\n" +
            "nine4jrlbhnpsixvkrcqvzsjj7\n" +
            "5twochgfgdsevennbmzmxfcrqfeight7qqkhqlrpdf\n" +
            "71mxlhzstppmffour1vrtd\n" +
            "82xdqfourkgbmzninefive9\n" +
            "ddcxpmzfljmfrqz3\n" +
            "five5kcdcxpl3four6\n" +
            "4lsfzhbc8\n" +
            "ninec5jnccxhzdtmtcdjhdrvktgtjjlbnsn\n" +
            "29mqjflc\n" +
            "9nine3\n" +
            "79sevencnj44x3\n" +
            "4fivenine4three\n" +
            "1lv\n" +
            "fourfour8\n" +
            "78xrszkgvptd\n" +
            "htmhxvsmppgxthreethreeeighttwo9\n" +
            "nntjqhnprfdknfs43ngmk4five3\n" +
            "gqncsix2rxxkjdschstwodknkninefivebfgq\n" +
            "eighteightqg777579\n" +
            "5ftkjlz7\n" +
            "qfqsix7\n" +
            "three79kk5vnd4gvvpjb\n" +
            "dsbxmgs2frm7eight\n" +
            "2kvlnkrbxxm2seventwosix11\n" +
            "nvneightwo8\n" +
            "5seveneightxvspone\n" +
            "fiveqhls26498\n" +
            "1snrdfgkc\n" +
            "425jqfpteighttwofive\n" +
            "8rsxmqsftrccbfour\n" +
            "7lb82vxzfk4sevenfive5\n" +
            "sevenhstzcvvtnjninehhtlnkrldx8pjsxkrlcjdfivezkqdfour\n" +
            "8six3dmr6shcm\n" +
            "6573fjkfndqrksixnine8six\n" +
            "twombmxvbcnine1mzhltonefdlp9\n" +
            "sevenqzvbpsslz5rone\n" +
            "8fdllsixonetglrngmdnvbsvjgflzonetwoseven\n" +
            "8nine6eighthlkj2\n" +
            "5rpx52\n" +
            "xseven69bbj1\n" +
            "qrthree8hkgcsqlrcf5\n" +
            "jhfrvzb5thgmbtcg\n" +
            "nntfour97vgknr\n" +
            "ltwone4hsrctbkfsz9jsfbhkm1seven\n" +
            "mgxnbgst84sevenfivetwo\n" +
            "gzdrfhqfcfdhxthree6sxxnmntpkz\n" +
            "3ninepkzhfq1\n" +
            "fouroneone7\n" +
            "8threetwo56bpjjps\n" +
            "4dvnttthkpgpdmcldvfour8two\n" +
            "2k\n" +
            "twomvx81fournbts47kkzggffpp\n" +
            "19seven\n" +
            "xcbhbdlrdfthreejxjsngllfkfive6pll\n" +
            "52nine8xffndctr1one\n" +
            "dvqh7eightdnlmntwofour8\n" +
            "5rfsvhh21vmcxrftwo1\n" +
            "rxfddhhxzlnlfvrk3eightzzhpthree\n" +
            "92twofhzeight\n" +
            "djxldch5rxkpzxtcn2smb\n" +
            "2nineninetmhkstmpcprcj5\n" +
            "brtronetwothree65\n" +
            "4four6one\n" +
            "7npgvjpr\n" +
            "sxvvbhvqcrftwo4fourrtjdnmk6\n" +
            "gv3twofoureight3qlhtjbzbqt9six\n" +
            "rlbrgkrsz818six3\n" +
            "fourcnsbr3rnzcggxqblhqjonesevensevensix\n" +
            "threenine5eightbx\n" +
            "klqrlnvgseven22vdrlvbseven\n" +
            "jzcnxdonenineseven4fivefourfour\n" +
            "4dxjsvlcvslqtmqpcfbbkqhfournine3\n" +
            "3vtjzclgklnszrv2sixddkcqgbxptrdhnlntrnr\n" +
            "one388qzqhmpzqlqtwo5four\n" +
            "sixnine441sgd9blsvbpnhpsds\n" +
            "732twothree\n" +
            "sevenqrvrvttnld9fqvvpgpnine39\n" +
            "threetwofour28\n" +
            "twofiveksvbnzfmzcbvqrnhsntstbrhf3\n" +
            "fjgcdtfn3\n" +
            "xgccx584six\n" +
            "2xsevensixtwo4six\n" +
            "xpheightnzdjgkrdmrjcnfprzvnine6cbtmsseven\n" +
            "nine1fivebgqtvsc8\n" +
            "dznrlhtfivethree43\n" +
            "sixthreerlmtvs7kkvtcx42rgpnljbsp\n" +
            "4frckxvvrd\n" +
            "eight4ldhkggpg\n" +
            "z57sevenxpfgntjnphcntj3bv\n" +
            "nthvgtxcck39vkpf7\n" +
            "64vzmzlvgeightonefive1tlvfggflj\n" +
            "fivejrjqzsfxgpdfbvcf58three1two\n" +
            "nine5five\n" +
            "ssphtp472xjfvlvzdl9oneightg\n" +
            "nine5xltblt9six\n" +
            "six28eightts5cckgvtnzmdgftxnine\n" +
            "tvhxmfeight7\n" +
            "zdnkjgcs43two9\n" +
            "q35bvblmmqhmnine5zeightwoj\n" +
            "gfkpfbn4\n" +
            "fivefiveone8\n" +
            "xnsddskzsb6xmfvkhbb54\n" +
            "nhsjx51ckpbntz\n" +
            "7kzxsgtnk5sixjlzlcsfqsxkxmvgnvthree6seven\n" +
            "fiveseven37\n" +
            "fourfqxkjct554\n" +
            "rsseven8zdz8xrxpnxv9rkqcnjcpgt1\n" +
            "jsixeightsevenrjpcqmdz5threeqfqgfqv\n" +
            "1threesix76tv4twonetgv\n" +
            "twonzhmrjlgvtvcj6\n" +
            "kxnpphq94three\n" +
            "zone4\n" +
            "5kp4eight87\n" +
            "93eight9seven\n" +
            "9zpz7zqxb1ssgkvtbzhrv8\n" +
            "sixvtdvvxmz2qcvrsnxcmtcszsnrnq84one\n" +
            "ninerggcxmlfqcpjhpjjtlvs5nine1seventtcmvrfr\n" +
            "five24\n" +
            "vpkf7onetwofive\n" +
            "8twosevensix1\n" +
            "53fivethreetgzcmzsm3fivefive\n" +
            "twokpjnmsc77\n" +
            "twofive53mfjjxq2\n" +
            "5four6fb4four3twocn\n" +
            "fivemvbgtsix55nine\n" +
            "five65rntfvpxpppkznlfour8\n" +
            "nine42cjtwo\n" +
            "eighttwothree9247twoeightwoxsq\n" +
            "sixlktcgr17six\n" +
            "kpbtwo57fmhdmzmqbt\n" +
            "442dkpxgnine6qbzf\n" +
            "8fourkmzjzltwo\n" +
            "ztgsrqkone78\n" +
            "dxzsnnsnj1mkctsix4qqbxscdfm9xvngln\n" +
            "four993kql7eightfour7\n" +
            "pdrtdxmpmm39qkppdjlttdn\n" +
            "ptpvc9mvlhfjkrthree9onesevenfourqbvzhdmc\n" +
            "dddkfcxrkfkphnhmjbrvmzqeightfourtwopzrmh8\n" +
            "38tt7psevenvgssvhfbzrhllbh\n" +
            "nine7fournine6sixgfcrrmnppj\n" +
            "fivezdmtj1\n" +
            "ninesix5eight\n" +
            "6eight6two2threetwoneg\n" +
            "ninenineseven4\n" +
            "5tpcvlsqqgv3fb8fsbtfivexbzdx\n" +
            "sixzxfxjmtm24one9422\n" +
            "sqbqtjgdr3eightnbjhzmbt\n" +
            "fiveone2nine9\n" +
            "8three4c3fdxnm81\n" +
            "seventwovnine4eightmlzhtkfour4\n" +
            "mfkf42\n" +
            "7threetwosix5\n" +
            "1qqgb74eight\n" +
            "ttrrsrsrqjtwo2sevenseven8twofour\n" +
            "onefivefour14hzdvdvvbrz9eight\n" +
            "bkqplctgnine28bptqbpfhgs\n" +
            "1zlhfourlqtljgxztjtseven\n" +
            "64two\n" +
            "gkfsvbgsone8three1ch\n" +
            "mmjqbmrk494qfbhgl9tdhsldsjvjgbq\n" +
            "kdnldkpfqlqsfivelndmxtbdfc5\n" +
            "9lgtxsc\n" +
            "xzrjpshsslqvbcthreetsixlql3khxbn\n" +
            "three99tcg8nineone\n" +
            "4jfive8thdhvbl8dkr\n" +
            "619fivecthgp8bcfszxrm\n" +
            "onetjjsmm8dtpkm\n" +
            "two62zlkgsevenhqdp3\n" +
            "8zfgtfnxvjjxgptxkpkdb1gkndcsbgvzxgqg1oneightq\n" +
            "7vnkhnssixkhrklsdbb96\n" +
            "3sixsix454four\n" +
            "htfxkcvbcbdpmlr42\n" +
            "5dspnxhkrvtmthreeseven68xnxbcb\n" +
            "fourxmjlnngjv4dcqninebbfprffgzs\n" +
            "three523eight\n" +
            "fnxfctsix1\n" +
            "6jx6cqbjqmzmz596nine\n" +
            "1three2eight1five\n" +
            "8twoprjjfsthreepqxmhc838\n" +
            "vlpdsntkqpxqdjzggtjfk8five8dthree\n" +
            "four8nineptrbrtlninecdseven1\n" +
            "tfvbjctfive49\n" +
            "four9fivecsqfs\n" +
            "fivefiveggrbf8vcdftdpzhc68fiveggr\n" +
            "sfvhspbgtj2\n" +
            "seven1two7bvdsq4seven4fmbfs\n" +
            "1hrcsbmcvcthree11\n" +
            "98two\n" +
            "rnvmdvhrthree6\n" +
            "3ksnfzfkrlx86dqjlftjdmtjrbfrsgf\n" +
            "twolsxrkone428\n" +
            "four6eightwokqz\n" +
            "five2sixnine1fourhdhms\n" +
            "six26\n" +
            "5seventhreedjsgshhtmlmpjk\n" +
            "14shpdfxxxzrfseveneightf\n" +
            "vprv9two6\n" +
            "nine3xqkpcdqfourfive\n" +
            "dtjsf923fourjdjzzsmxjh\n" +
            "2fivexdvlgrngjbrqdvzx\n" +
            "6f\n" +
            "five191htbfdg2eight\n" +
            "qmfblcvxfzph8two\n" +
            "ppdkvczsthreexhvfslpncbpqrqkz3k\n" +
            "896\n" +
            "nrzpqk3fivesldclpcbfmdtbbhpxonethreeeightwor\n" +
            "7cnn871\n" +
            "sevenfgnc58lllvzfmnfqsshvjhqpgvx\n" +
            "6hfrhvklvpp\n" +
            "onekcrcpsjtsndskmbtvmcd1seven\n" +
            "6twoeight5vmdgvhhjsqfourjkns6\n" +
            "zlgseven3sevenbfgzgpbmhlbtx6fqpb\n" +
            "7pone828\n" +
            "vc7cjzjc94\n" +
            "pmmzhthree36twofour4\n" +
            "q5onesqltxfourkxx8\n" +
            "fivedsvbdtqkrzssix2six\n" +
            "sevenone2four4pmn\n" +
            "fivesseven47lndonesevenvfdvkp\n" +
            "vfxzlzvt7\n" +
            "hcqf179\n" +
            "6eight3\n" +
            "hmftwone37dzbmone\n" +
            "qonehzfj4\n" +
            "eightonesix7\n" +
            "6pfournine\n" +
            "onefivehdt88five\n" +
            "three2eighttwosix971\n" +
            "xxtffpnkd6mxsjmhbgp2four\n" +
            "foursixmxrsmvhrx97\n" +
            "dqkc9njlxh\n" +
            "nine2fivexjvsmthree\n" +
            "2597frctprbrsix7nbcnktxpdz\n" +
            "6vvtlzd29ftgmjbjjpscbvkcmfzpcj\n" +
            "bpmnr2kpdsxseven\n" +
            "twofoursix7seveneight\n" +
            "trcfdlp5qnxmdeightqmzd\n" +
            "seventwo7blpfqnsqjrbgzxvzxfourdtstcrv\n" +
            "z54five\n" +
            "llrjhdptlrzzjngrqvksbrmhttwoqfmlntj8\n" +
            "fhthpcrrthreethree7fourfour2\n" +
            "sixfzgnfour81threepdpsix\n" +
            "3ddxksjkcxltxgr5one7eight\n" +
            "6tskvfz\n" +
            "1twobsdnmmvzz4three\n" +
            "15ljtrqkh7xmqbmbn\n" +
            "22threenine2fkpzshztdhmdcxdz2\n" +
            "9seven12six\n" +
            "9ninethreesbqcjqvx\n" +
            "133bphdqcsdlbgmhjqkhdnvtgvfive\n" +
            "1ninezkvjfmmttvldxq\n" +
            "fourxqjxmjvb7\n" +
            "foureightthree4\n" +
            "6one8\n" +
            "two2twothreervhzqnl\n" +
            "3ninesixsixtwo7sixeightone\n" +
            "nineninenine6ps3fourmhkspqqz\n" +
            "bklcqxggmp9ktzvmlvmmeight18\n" +
            "1onesix2eightnd89szcklv\n" +
            "pttqvhsdxp28htkfttpnfourseven\n" +
            "5eight9xjgzrxqskttjhcb8ghlxjhfourht\n" +
            "eight2l714\n" +
            "9xcqnbfive6fivethree32\n" +
            "zgmbvjtwoone4\n" +
            "rvxfrdhqq4sbsnlrslh\n" +
            "ninethree9two\n" +
            "6sevenmdvsdqxt3vnzdgninejkdjmzngckfcdh9\n" +
            "jskmdkhhn443onefjdrhqn\n" +
            "2cnkvbd\n" +
            "seven5rh6eightmcpkvcdrcfivexntt\n" +
            "eight1gqtnkdmvsglvkone87\n" +
            "four8six\n" +
            "67ninecvqcpxpfqphx\n" +
            "3schxdptgtgfjdbsffxg8xmhxvmrnvfive\n" +
            "mlxqgftbrkvgkczkone65two7\n" +
            "jzrttfghtqonezjpbxds3fiveninevppqqqc\n" +
            "4sevenjqbnpjlhj\n" +
            "4573one\n" +
            "eightclqsjjjss6\n" +
            "one5sr3klmrccnrhd8\n" +
            "jczvxzbvvctxdzmcg3sixtwotfvkcl9jqffdh\n" +
            "cjtslmnine8six\n" +
            "rrzktthree3two6eight\n" +
            "sgeightone23five6ninekstjcksnst\n" +
            "6nhkdjm2fouronehrnd73\n" +
            "two56six\n" +
            "6six2xmczcgbpj3\n" +
            "fivevdhnpjxcgrmc963\n" +
            "6746rrplshznckgxrksgczqthree55\n" +
            "onehxkrhhkczt2pxsfvlgthree\n" +
            "9threelgbzzjxzfsjrmvnvcsqffour\n" +
            "nine7gfivefoureightsix1\n" +
            "3seventwoseventcbsixllmhlmjbtqtfpfrjqbghd\n" +
            "1eightzdskcnhbm\n" +
            "rlccvmpnzfoursix9\n" +
            "nine2xbmfourfourzncxtjgkn1\n" +
            "1264cfmm\n" +
            "smntmjr53sevenmjghvnvhgrhxq6\n" +
            "7szrqhlmjkfqspnvseven\n" +
            "29krc\n" +
            "hpj37eightgfzsl95gdcdbtsxqh\n" +
            "xcv736\n" +
            "eight3fourhtb43\n" +
            "threethree967rlpk4nine\n" +
            "seven2931nhxpkppdv445\n" +
            "3eight5hvlxjspmsdfivedrfsmvzr\n" +
            "zgvvcpthree83twofcvqnine\n" +
            "seventwo2bgxcnbmzone\n" +
            "threesix5tfthree862\n" +
            "8brzvkxz\n" +
            "713srdjqdnbbrvxhn4\n" +
            "3t7fourtwoeightmjqqjbknp8\n" +
            "btltwonefour2rjmfmlsbmdfp\n" +
            "8sixthree1\n" +
            "fourthree3sixhphctrfiveonesix\n" +
            "eight11fivesix\n" +
            "ppltwonepcmjdmtc2sixjpqnvpczbmtplqcsz\n" +
            "pfn2\n" +
            "pfvqrm54mhvzmqmgtwoneckj\n" +
            "rpsevendfv2onethree\n" +
            "46hrhrkkpp74threesix\n" +
            "fsrr8\n" +
            "7twofourfourcpcbfourfivenine\n" +
            "onethreefive71rfhmtlzb72hzhl\n" +
            "t71three6hdrnfour\n" +
            "llmdhfeight9\n" +
            "lgzxltwo3twoktxdltzqv\n" +
            "sixhlmbbzlqflq4mlsevenmsdsfqsqvnine\n" +
            "3lpsltdnine\n" +
            "three1sixfour2\n" +
            "3sixgcdf1\n" +
            "four21\n" +
            "84foursixclbmxpctn1bjsl\n" +
            "brsxfkdp4xzvggqbqtxsx6threethree\n" +
            "vccz3threetwoone59\n" +
            "sixjmpdtc1\n" +
            "tjshpfbvmllqfiveeightfzvdjsczqxg2\n" +
            "twolvzsmjjseven8\n" +
            "2vnbbrtzts9mxzsllltone99jvsxkc6\n" +
            "nine3qninesix\n" +
            "8qdthreetch\n" +
            "two1ktnbjxqsjsixonepljgnmrgnb\n" +
            "one2one81tsvpvj85spn\n" +
            "31\n" +
            "one2ninelzpone4\n" +
            "twofourthreejgdbthree7three5two\n" +
            "2316fslp5\n" +
            "threettcdspbsix3three2mpkxzspltr\n" +
            "5sevenblffmddx5xmqcbdrxvhmqtwo\n" +
            "1threethreejxplkj\n" +
            "plqqpf3fhsgjclhg4sr\n" +
            "fourone1fivefive1fourpdkjszpcsd\n" +
            "8lhthrsptzbgzllzkrhpqdbkfivedrrtk\n" +
            "1ninefive2threevbflj\n" +
            "4sixfiveeighttwo3threefive\n" +
            "qvcxfrjgm6threetwoeighttwoneg\n" +
            "2bhfpjnxbttwottrvdmpssgjjvqjhkdskmxjqone\n" +
            "18czsfmq\n" +
            "58dlqninerqt4pdjzktspssixlgdxrddt\n" +
            "3sevenrcsqtmfrhk694\n" +
            "93ninevttdgh\n" +
            "2dxsmtnnqseventwo\n" +
            "onenrdfhqg3six\n" +
            "jfjeightwobstfsln8dvvdmgdhgxx1one7nine\n" +
            "fndrpmkpbtqgk7six8nhfpnv4hfvcjnjh\n" +
            "3hxtvzbhqbhkrtqmphfivej2\n" +
            "seven818\n" +
            "czgrscnine3\n" +
            "3pltt62three5seven\n" +
            "2mvmpqrgdm5\n" +
            "six52three1sixthreeeight9\n" +
            "onecbshrmsrpjlkkrrnine7mvx\n" +
            "five34\n" +
            "sixjlfsixone9nnzhkvldeightfourpbf\n" +
            "four47nine7\n" +
            "three462fivefour6\n" +
            "nsixonefivefive6twochreight\n" +
            "9twofourppg9three\n" +
            "lcpggjmppmnkktfvszbl7qmxqrseven\n" +
            "ztwotwothreekdftqtqmpeightznhnine7\n" +
            "bptgpcxxknsgxbznnxzhnzx59rvsj\n" +
            "8ntnpqdlkfctckk7qbcfiveone\n" +
            "1cvhlrj5five22vrpphp1\n" +
            "m9bbpngzzrsix\n" +
            "hbflvlnzln9xhfdsfqqxvnzdpzeight\n" +
            "22sixfive1fourbpncphnnkrlzxz\n" +
            "three8fivecnvgtnpmfkzggttcjonerxq\n" +
            "qrfksfzjvseven6xqsmdr3two3svdjjb\n" +
            "48xxtqpnxthmjbzldrv\n" +
            "gblqlbb9rzfnr\n" +
            "onehc78sixsevenonepfchbfmgzp\n" +
            "lptwonefiveb1131\n" +
            "lzcbfourh9qvtsggsthreejnjjnmtf\n" +
            "1shljseven\n" +
            "1gdghnzhqlseveneightsixsevenmblqvjpxd8twonejm\n" +
            "mzfgmtndztwo3xlvxdcsseven\n" +
            "59hvnjvjgxxtljdsgrjjpzcmxgninenineone\n" +
            "fivetwothreemdjcsevenkcljqpktwo9\n" +
            "toneightonelb4threetmldjmvjlfrnmkeightctjxdqhrcjczcr\n" +
            "six4jnlftktspjthree23seven1xfbrkh\n" +
            "fourtwo7fourqzmcrseven4\n" +
            "clrgvbgcbb1twonekgr\n" +
            "9one9hbdmnzldksix\n" +
            "three161vfrdvbh7seventwo\n" +
            "28rxckppjhxn139sevensixmd\n" +
            "sevenfive5twobdxhzseventlf\n" +
            "xm48781four\n" +
            "tdsqpmcfdjvqtzt56nzlbdrm\n" +
            "fglpgdqonemsdljnq1\n" +
            "5foursvgbnthn\n" +
            "eight14dcvcvgrlkm\n" +
            "nine8kxjvjskbvcdmmbsgcxpheighttwofour\n" +
            "knsplfsix6cqkhsevenlkknhdnvl3\n" +
            "eight47fnhssqvdt9vzkr8\n" +
            "dcjx1rzxfk3seven1twovzcsddtckg8\n" +
            "1onecqxcszfqrcvm5lvpb42four\n" +
            "sqclpndjgf7\n" +
            "kbxbhrgxsfbljnlbd1lflxpcm298\n" +
            "nine1one\n" +
            "nineseven1one\n" +
            "9stlxptznqgcbjvdgt5ninesevenlkxsix\n" +
            "xlhl2nine5\n" +
            "jqpx1gbxrtdv3\n" +
            "981six\n" +
            "f795bkkjmmddhvm\n" +
            "2ninexblcgmhxxceightwop\n" +
            "twoxkmb9fvmvljzjd\n" +
            "3pgdsc2onestzh\n" +
            "zpmmdf912three\n" +
            "9fivedvn\n" +
            "five23five3\n" +
            "sixonexxgxdqjsfmeighteight2three\n" +
            "4eightxbss4twotwo\n" +
            "six8mcbl5shdgpglbdrn\n" +
            "4sixthree7sevensevennine\n" +
            "7pknqttzlxfive4\n" +
            "nineeighttwotwodbdjonethree3hp\n" +
            "3972oneeight7\n" +
            "tbsqftsbnhbgljmjmk12pmpfplhqb8x\n" +
            "sevenfivesdrsevenfourfive5qfvqsxeight\n" +
            "lxvfv366one3tvlcbfhone\n" +
            "4vqlcfnineghvkfm\n" +
            "qdhfqqeightone3595one8eightwov\n" +
            "rfsdbjkk48xxeight\n" +
            "3fiverbspbvtpg3ninempxcrkfour\n" +
            "37ninehnpdmdqcgvjfour9\n" +
            "164two\n" +
            "twoonetwoknlffnine4two\n" +
            "eightthree9zhtntdsf5mfsklckp\n" +
            "zrznzfxpmqfive4ppjkjninetwo6seven\n" +
            "9tnztckdmqdmcthreejgxrlhmninermztwo\n" +
            "qoneightsixfoureighttwo2kjlpsf\n" +
            "fournine315fiveone3\n" +
            "hcrmlngq73eight39four5\n" +
            "kqtmfsdfxhvhnsxmmbtbk7sixsixfive1xnb\n" +
            "three7eightnine\n" +
            "sixfivetwoeight14eighttszxffvhmrn\n" +
            "7ctxfoursjqnghg5sixtwo\n" +
            "one4b8\n" +
            "123five8six\n" +
            "two6seven7dplzhncqx\n" +
            "four7ninedqfplv7threenineseven\n" +
            "sixdqjcllsgj28sixsbgcxbdkeightb\n" +
            "415kmxtvpdthree\n" +
            "ninectmc3two\n" +
            "fivefiveseven2two4\n" +
            "mvsg44fourrxsmdcxpbzslzdhbgqlxeight5\n" +
            "bxtwoneone7bxxmeight7rp19\n" +
            "sv2chpqrztht8eightfour8nine4\n" +
            "dxlgdfqvkdgvdxlcxkht9\n" +
            "sixeight6ffivethreesix\n" +
            "qjmprhcxdgvrrqdmlzbbpkns8nine\n" +
            "ninedltfrzpq8\n" +
            "8rjqseven\n" +
            "273phmpjmf26clqgmckqrh\n" +
            "6dqbgzgqbgrhqqmmnjpmvsdbjxkgs\n" +
            "fvpvclz4msmtzdffplbhkpt311ss\n" +
            "zrvhlnhfxnzthree7\n" +
            "oneonezclqbxxd6ninesixthreefour2\n" +
            "q7vrltqqtkd9zmxdtcsrtwo\n" +
            "vpxl9zldgphfjk3hz4\n" +
            "clpllv8cmpgdvbfmp\n" +
            "7xxdlnfmseven475one\n" +
            "6cfgvvzbk863sixzlvv\n" +
            "25vxrseven\n" +
            "5eight4qbztpc3hbzvvpxscgcn5\n" +
            "eight7bqqtbdqmnine16rh5\n" +
            "threempjzsmbtj2\n" +
            "nineseven76kdbff8\n" +
            "93twoeightwoff\n" +
            "6threefiveone9\n" +
            "nmmzcpgnjnpzr6threeptconeonetwo\n" +
            "fivethreetwozmrcg5six6\n" +
            "onesevengrcvnhdlfive5seven\n" +
            "fourfourvpm2lsixfive\n" +
            "2four2three\n" +
            "seven88\n" +
            "mcxsggtwo1eight5threezqvk21\n" +
            "tjfmcvsbvcqch774two5\n" +
            "two51vgfzfszrrcqnggr\n" +
            "threemqkxvthree2\n" +
            "2jftwothreeseven68\n" +
            "rhjszm7brmnclrhxsrck\n" +
            "drhxztpvfp9eightxxsdsphrsix13\n" +
            "6pldmbdxhgrqxd7\n" +
            "sixxlstqkx9bltfnktdrkeight\n" +
            "vzhpgmtmk5five885jvdxkvmb\n" +
            "fivetnldpkbnqrptone94four\n" +
            "3zqtwo8\n" +
            "zshvvcjtvbmjpqgljfivebrcsl2six\n" +
            "ninecv2dlhgzteight2\n" +
            "dhlfdgbgheightqdzk1two5zbggf\n" +
            "eight2t7\n" +
            "4nqbjfxtklzfour3\n" +
            "8qrdzcphsvndbszdnbcndfszrhmvzcszzsgshml2zgbgjx\n" +
            "nineqttcd4five4gfjlgktkdlrmctv7\n" +
            "nine4xfgmfvgg\n" +
            "3mtmhkcsixbbpvzgnklmdxvkrninezlnrds\n" +
            "txsmflhl7qqlcbn47\n" +
            "six4kvvfour88cfmzds\n" +
            "3sgfourbphmcvxfqqzgfthgnhf6\n" +
            "3fqgdnqtwoeightlzplmjlptzkfour\n" +
            "9fivenj9sixgtmghntstjp\n" +
            "794jljzxngthreeknjkv9\n" +
            "513five\n" +
            "ssix8three1twofivegk\n" +
            "ninethreeeight4vfqbgbxf5\n" +
            "sgxldeight9\n" +
            "six189\n" +
            "vdcsbmmcvbfqtgqgfoureight6gdsznd6\n" +
            "p6\n" +
            "58ckjgkrstcgtfm3seven\n" +
            "367\n" +
            "shlnlp9sixvvbctrkqd75fournine\n" +
            "mqltnzcrqmljgmseven3bqqhhjncnmtwotklrtxgbcn\n" +
            "8fdgshseveneightthree1fourkp\n" +
            "8sevendsmpshkthreetwoztwo1qtpdxr\n" +
            "mfive97xs\n" +
            "xdfourmvtxt3twofivenhtznksix\n" +
            "one56ncxzxdfv\n" +
            "sevenklqngxp27jmjpbdsskz\n" +
            "43zlpqsjz51twogdmszvl7\n" +
            "4v35q\n" +
            "mtwo98xxhxqshv1\n" +
            "fivethreelcnhjcsr4tnbg\n" +
            "65r\n" +
            "mhfxxgdbthreesix3rdpfksvpxqbjssqmksxbkqxk1\n" +
            "mnthlsxffourfour6threezcqeightwosk\n" +
            "qjgr1\n" +
            "fourone7eightqhsrxpjxftwo3\n" +
            "gd7qlsjvps\n" +
            "one5rsevenonenine\n" +
            "eight95kzddddkmjfbhjtmgpccxqqfbszstxqlplmtbpthree\n" +
            "sixbddthree58\n" +
            "xfoneight8sevenone3\n" +
            "fqdhrvone92nine\n" +
            "ffhtwonesmcmlddsix15nineqgkgbgvnj\n" +
            "pdnmmlxzk3814\n" +
            "trsmkshtfeightnine5\n" +
            "hjqdjh65twoqrqcxseven97\n" +
            "66twoxdlmlqrhk7three\n" +
            "m841\n" +
            "lk4\n" +
            "591vqcqrdzsddl6\n" +
            "jgvmbdflph5frnxkkdplseven\n" +
            "fivebmjmlcs75seveneight\n" +
            "fivefour9bcslbnr9fourtwotnzqshcvoneightnz\n" +
            "sevenxbqngpxmpqnxbdmxhsdkkdbb2\n" +
            "vxqeightwokkdsdcgq7fgjlbcnhlzgjxtcntx\n" +
            "7five4nine7twocbjsctoneeight\n" +
            "fourfour5mqdqfbnineqvksvbtnfive\n" +
            "67four4qrbddqcthree\n" +
            "28vxtbdcvqxrlrqm\n" +
            "2nine4mltwospmqm6three\n" +
            "fmzgbtkbckmtk15seventwoone\n" +
            "5bjnc\n" +
            "two9one5eighttsptkjflxfvzvp\n" +
            "qcnlfjfpdgh8onestone\n" +
            "6kjbqqczjktsixk1p4gzjrcvc\n" +
            "crdhznlrrc8qmrgpvlrd3573\n" +
            "five55twofiveqhxmlnlscs6\n" +
            "onegrcxflkqb6fourtwochltwokpnxtxmzfive\n" +
            "five6qcbjmffzktsmhzzdtnqkc\n" +
            "919eight\n" +
            "pboneightseven9rppzrmdrcfive75three\n" +
            "gdjtsgbjzkgxbnzk9qpgblmqsmssvqzcpmffneight\n" +
            "vbfrxninetwofive123\n" +
            "foureightseven9two\n" +
            "53931sevenlcsxmlzthreelnsjtcm\n" +
            "dphhkqnptwot2sk4\n" +
            "94fourpvfrtgrms\n" +
            "four2gxnc8x\n" +
            "nine9mkfljgc\n" +
            "eightmxj83sfr1\n" +
            "9qlldctxqttonejtsxhdzjf2nrpmvpgeightnine\n" +
            "1threebjgpnsmltszbjmbvpctvljjzvbjb\n" +
            "cgszmdlcssix56jphvdsbh5\n" +
            "ljjlmxgtkrqpldbllmjsctfv1sevendgnx477\n" +
            "94mlgfrfive3rlbv4nine\n" +
            "12tr3kcbtjxfxrsevendjrzgfqb7\n" +
            "7tlsvjfive3\n" +
            "fourbgksix9lnine636\n" +
            "rpvftxcnone2\n" +
            "bjgtmdrgrrrpxndlmvmgl829428\n" +
            "hfjjkjg1seveneightflkhhmmd\n" +
            "3one273\n" +
            "nkkxzlrkgfonesevenfour7twompjpqdsvpp\n" +
            "qctwofive7flqqkmsqplbb7eight4\n" +
            "9bkshzspgz19vhmsseven\n" +
            "17eightthree4bq\n" +
            "1three3\n" +
            "rdrxmvddjrdvmczg8fourxgskh4fourddcm\n" +
            "eight85nineone6onehxfcqhdbb7\n" +
            "5seven8threemvjsmmgmone2\n" +
            "7five7gfnnfbs4fourfive\n" +
            "47vkfndgnlv16four\n" +
            "1mxdnp147ftrzv8\n" +
            "1svlfzctbrbjprkmpz4xtbccfxhnvfqmhzt68\n" +
            "fourqsgxnxthreeeighttwo2seven1nine\n" +
            "57sixsix2sevenvkxrsevencmmgv\n" +
            "5jlkfmtwoseventhreeoneightbsr\n" +
            "zpsevenfouronexftsphg731\n" +
            "15twosix774\n" +
            "bbpthreeonenpkknbxn2kdqbrbr\n" +
            "dc7mqnzhmtdfr18\n" +
            "fivefivethree75two7three\n" +
            "lbqvxmgfivenine3ninefive1\n" +
            "sgpnsmdqb5seven8eight\n" +
            "hclzmmbt3gthnf\n" +
            "lpxtfzvs6twosevenfour1dxrdnkfive\n" +
            "onektc4three\n" +
            "337\n" +
            "nflntqzlcfourgbgkcldrvbx8five53\n" +
            "8nkmkssgmlgmxhvpdgjseven\n" +
            "nine78twohnthree9\n" +
            "9ninesixgtjqbksix392\n" +
            "sevenonegfmlxzzrm35nt\n" +
            "xmmrcjtspfive8sixsixt1\n" +
            "tpbdxblvfqblcqndseventhree22\n" +
            "2shhzch\n" +
            "fourtwo5ssdmsn51eight\n" +
            "9rvxckfrrvsix\n" +
            "tgfcgdm1qsx3four2eightcctqd1\n" +
            "kxqfltbrfhpkbsmtthreethreeone3\n" +
            "zrxprsixfiveone8bvbdmxjzbmthree\n" +
            "fpqjfcpheight4twofive5kpcnntbnnq4tcfbkqh\n" +
            "bhjkzdmmrfivetsxlhthreeddchsix5\n" +
            "5tck83cseven9nine\n" +
            "two2three\n" +
            "6oneighthlf\n" +
            "572hcvfdbgt9twoonechngccmqc\n" +
            "74eightrvtconebgjbpnqlslcs\n" +
            "nbmntwolntd1zvzplfzthree11seven\n" +
            "kpzfgpxdonesix2fourninefourfour\n" +
            "fbdqzbmjnkmqcgeight5five\n" +
            "425six14two46\n" +
            "jhctmxconelfkgmprnfourseven8twofkjvlvnjgd\n" +
            "twonrpvnnmvkh2threejzcpz";

    public static void main(String[] args) {
        int total = 0;
        HashMap<String, ArrayList<String>> legend = new HashMap<>();
        ArrayList<String> nums = new ArrayList<>() {{
            add("1");
            add("2");
            add("3");
            add("4");
            add("5");
            add("6");
            add("7");
            add("8");
            add("9");
        }};
        ArrayList<String> threes = new ArrayList<>() {{
            add("one");
            add("two");
            add("six");
        }};
        ArrayList<String> fours = new ArrayList<>() {{
            add("four");
            add("five");
            add("nine");
        }};
        ArrayList<String> fives = new ArrayList<>() {{
            add("three");
            add("seven");
            add("eight");
        }};
        legend.put("1", nums);
        legend.put("3", threes);
        legend.put("4", fours);
        legend.put("5", fives);

        String[] lines = input.split("\n");
        for (String line : lines) {
            String firstNum = "";
            String lastNum = "";
            for (int i = 0; i < line.length(); i++) {
                String charConvert = String.valueOf(line.charAt(i));
                if (firstNum.isBlank()) {
                    if (legend.get("1").contains(charConvert)) {
                        for (String num : legend.get("1")) {
                            if (charConvert.equalsIgnoreCase(num)) {
                                firstNum = num;
                                lastNum = num;
                            }
                        }
                    } else if (legend.get("3").contains(line.substring(i, i + 3))) {
                        for (String num : legend.get("3")) {
                            if (line.substring(i, i + 3).equalsIgnoreCase(num)) {
                                firstNum = num;
                                lastNum = num;
                            }
                        }
                    } else if (legend.get("4").contains(line.substring(i, i + 4))) {
                        for (String num : legend.get("4")) {
                            if (line.substring(i, i + 4).equalsIgnoreCase(num)) {
                                firstNum = num;
                                lastNum = num;
                            }
                        }
                    } else if (legend.get("5").contains(line.substring(i, i + 5))) {
                        for (String num : legend.get("5")) {
                            if (line.substring(i, i + 5).equalsIgnoreCase(num)) {
                                firstNum = num;
                                lastNum = num;
                            }
                        }
                    }
                } else {
                    if (legend.get("1").contains(charConvert)) {
                        for (String num : legend.get("1")) {
                            if (charConvert.equalsIgnoreCase(num)) {
                                lastNum = num;
                            }
                        }
                    } else if (i + 5< line.length()) {
                        if (legend.get("5").contains(line.substring(i, i + 5))) {
                            for (String num : legend.get("5")) {
                                if (line.substring(i, i + 5).equalsIgnoreCase(num)) {
                                    lastNum = num;
                                }
                            }
                        }
                    } else if (i + 4 < line.length()) {
                        if (legend.get("3").contains(line.substring(i, i + 3))) {
                            for (String num : legend.get("3")) {
                                if (line.substring(i, i + 3).equalsIgnoreCase(num)) {
                                    lastNum = num;
                                }
                            }
                        }
                    }else if (i + 3 < line.length()) {

                    }
                }
            }
            String stringSub = String.valueOf(firstNum) + String.valueOf(lastNum);
            int subtotal = Integer.parseInt(stringSub);
            total += subtotal;
        }
        System.out.println(total);
    }
}
